from django.urls import path
from . import views

urlpatterns = [
    path("",views.home, name='home_url'),
    path("about/",views.about,name='about_url'),
    path("smart/",views.smart,name='smart_url'),
    path("contact/",views.contact,name='contact_url'),
    path("login/",views.login_view,name='login_url'),
    path("register/",views.user_registration,name='register_url'),
    path("smart/<int:pk>/detail", views.smartdetail, name='smart_detail_url'),
    # path('blog/', views.blog_veiw, name='blog_url'),
    path('blog/<slug:slug>/',views.single_blog_view, name='single_blog'),
      # New URL pattern for direct access to blog_view without any parameters
    path('blog/', views.blog_veiw, name='blog_url'),
    path("ad/",views.AdminIndexView.as_view(),name='Admin_home_url'),
    path('phone/comparison/<int:phone1_id>/<int:phone2_id>/', views.phone_comparison, name='phone_comparison'),
    path('logout/', views.logout_view, name='logout_url'),
    path('profile/', views.user_profile, name='user_url'),
    # =========================== url for adding ==============================
    path("admin-phone/",views.AddPhoneView.as_view(),name='Admin_phone_url'),
    path("admin-model/",views.AddModelView.as_view(),name='Admin_model_url'),
    path("admin-resolution/",views.AddResolutionView.as_view(),name='Admin_resolution_url'),
    path("admin-platform/",views.AddPlatformView.as_view(),name='Admin_platform_url'),
    path("admin-memory/",views.AddMemoryView.as_view(),name='Admin_memory_url'),
    path("admin-display/",views.AddDisplayView.as_view(),name='Admin_display_url'),
    path("admin-dimension/",views.AddDimensionView.as_view(),name='Admin_dimension_url'),
    path("admin-connectivty/",views.AddConnectView.as_view(),name='Admin_connectivty_url'),
    path("admin-camera/",views.AddCameraView.as_view(),name='Admin_camera_url'),
    path("admin-brand/",views.AddBrandView.as_view(),name='Admin_brand_url'),
    path("admin-body/",views.AddBodyView.as_view(),name='Admin_body_url'),
    path("admin-battery/",views.AddbatteryView.as_view(),name='Admin_battery_url'),
    path("admin-announce/",views.AddAnnouncedView.as_view(),name='Admin_announce_url'),
    path("admin-list/",views.phoneList,name='Admin_list_url'),
    # ================================ update url ======================================
    path("phone-update/<int:pk>",views.Phoneupdate.as_view(),name='update_phone_url'),
    path('user-list/', views.UserListView.as_view(), name='user_list'),
    path('user-create/', views.UserCreateView.as_view(), name='user_create'),

    path('user/<int:pk>/update', views.UserUpdateView.as_view(), name='user_update'),
    path('model/<int:pk>/update/', views.Modelupdate.as_view(), name='model_update'),
    path('camera/<int:pk>/update/', views.cameraupdate.as_view(), name='camera_update'),
    path('connect/<int:pk>/update/', views.connectivityUpdate.as_view(), name='connect_update'),
    path('display/<int:pk>/update/', views.Displayupdate.as_view(), name='display_update'),
    path('brand/<int:pk>/update/', views.brandupdate.as_view(), name='brand_update'),
    path('battery/<int:pk>/update/', views.batteryupdate.as_view(), name='battery_update'),
    path('platform/<int:pk>/update/', views.platformupdate.as_view(), name='platform_update'),
    path('resolution/<int:pk>/update/', views.resolutionupdate.as_view(), name='resolution_update'),
    path('dimension/<int:pk>/update/', views.Dimensionupdate.as_view(), name='dimension_update'),
    path('memory/<int:pk>/update/', views.memoryupdate.as_view(), name='memory_update'),
    path('announce/<int:pk>/update/', views.announceupdate.as_view(), name='announce_update'),
    path('body/<int:pk>/update/', views.bodyupdate.as_view(), name='body_update'),
    path('phone/<int:phone_id>/review/', views.review_section, name='phone_review'),
    path('write_review/<int:phone_id>/', views.phone_review, name='write_review'),

    # ============================= url for list ====================================
    path('list-announce/',views.AnnouncedListView.as_view(), name='list_announce_url'),
    path('list-battery/',views.BatteryListView.as_view(), name='list_battery_url'),
    path('list-body/',views.BodyListView.as_view(), name='list_body_url'),
    path('list-brand/',views.BrandListView.as_view(), name='list_brand_url'),
    path('list-camera/',views.CameraListView.as_view(), name='list_camera_url'),
    path('list-connectivity/',views.ConnectivityListView.as_view(), name='list_connectivity_url'),
    path('list-dimension/',views.DimensionListView.as_view(), name='list_dimension_url'),
    path('list-display/',views.DisplayListView.as_view(), name='list_display_url'),
    path('list-memory/',views.MemoryListView.as_view(), name='list_memory_url'),
    path('list-platform/',views.PlatformListView.as_view(), name='list_platform_url'),
    path('list-resolution/',views.ResolutionListView.as_view(), name='list_resolution_url'),

    path('announce/<int:pk>/delete/', views.AnnounceDeleteView.as_view(), name='announce_delete'),
    path('user/<int:pk>/delete/', views.UserDeleteView.as_view(), name='user_delete'),
    path('announce/<int:pk>/delete/', views.BrandDeleteView.as_view(), name='brand_delete'),
    path('battery/<int:pk>/delete/', views.BatteryDeleteView.as_view(), name='battery_delete'),
    path('body/<int:pk>/delete/', views.BodyDeleteView.as_view(), name='body_delete'),
    path('camera/<int:pk>/delete/', views.CameraDeleteView.as_view(), name='camera_delete'),
    path('connectivity/<int:pk>/delete/', views.ConnectivityDeleteView.as_view(), name='connect_delete'),
    path('dimension/<int:pk>/delete/', views.DimensionDeleteView.as_view(), name='dimension_delete'),
    path('display/<int:pk>/delete/', views.DisplayDeleteView.as_view(), name='display_delete'),
    path('memory/<int:pk>/delete/', views.MemoryDeleteView.as_view(), name='memory_delete'),
    path('platform/<int:pk>/delete/', views.PlatformDeleteView.as_view(), name='platform_delete'),
    path('resolution/<int:pk>/delete/', views.ResolutionDeleteView.as_view(), name='resolution_delete'),
    

]
