# Generated by Django 4.2.3 on 2023-07-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='internal',
        ),
        migrations.AddField(
            model_name='memory',
            name='RAM',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='ROM',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
