# Generated by Django 4.2.1 on 2023-07-24 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0003_rename_is_candidate_customuser_is_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='anounnced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announced_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('battery_type', models.CharField(max_length=50, null=True)),
                ('fast_charging', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('url_to_image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('bulid', models.CharField(max_length=50)),
                ('Sim_Card', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='brands')),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.IntegerField(null=True)),
                ('feature', models.CharField(max_length=50)),
                ('video', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Connectivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wlan', models.CharField(max_length=50)),
                ('bluethooth', models.CharField(max_length=50)),
                ('gps', models.CharField(max_length=50, null=True)),
                ('nfc', models.CharField(max_length=50, null=True)),
                ('infrared', models.CharField(max_length=50, null=True)),
                ('radio', models.CharField(max_length=50, null=True)),
                ('usb', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_type', models.CharField(max_length=50)),
                ('size_inches', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_slot', models.CharField(max_length=50)),
                ('RAM', models.IntegerField(null=True)),
                ('ROM', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50, null=True)),
                ('is_waterproof', models.BooleanField(default=False)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.battery')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.body')),
                ('connectivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.connectivity')),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.display')),
                ('main_camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_camera', to='compare.camera')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.memory')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='phones')),
                ('name', models.CharField(max_length=50)),
                ('Phone_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.model')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.brand')),
                ('released_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.anounnced')),
            ],
        ),
        migrations.CreateModel(
            name='Plattform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_sys', models.CharField(max_length=50)),
                ('chipset', models.CharField(max_length=50)),
                ('CPU', models.CharField(max_length=50, null=True)),
                ('GPU', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.phone')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('text', models.TextField()),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.phone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='model',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.plattform'),
        ),
        migrations.AddField(
            model_name='model',
            name='selfi_camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfi_camera', to='compare.camera'),
        ),
        migrations.AddField(
            model_name='display',
            name='resolution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.resolution'),
        ),
        migrations.CreateModel(
            name='ComparisonHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_1', models.CharField(max_length=100)),
                ('phone_2', models.CharField(max_length=100)),
                ('comparison_result', models.CharField(max_length=100)),
                ('comparison_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='body',
            name='dimensions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.dimensions'),
        ),
    ]
