# Generated by Django 4.2.3 on 2023-07-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0003_remove_camera_modules_camera_module_alter_memory_ram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='is_waterproof',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='camera',
            name='module',
            field=models.IntegerField(null=True),
        ),
    ]
