# Generated by Django 4.2.1 on 2023-07-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0004_anounnced_battery_blogpost_body_brand_camera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(null=True, upload_to='brands'),
        ),
    ]
